site_name: Resources for Technical Writers
nav:
nav:
  - Home: index.md
  - Technical Tools: 
    - Technical Writing Tools: technicalwritingtools.md  
    - Flare Basics: madcapflarebasics.md
    - MkDocs Tips: mkdocstips.md
  - Document Planning: 
    - Doc Planning: docplanning.md
  - Style Guides: 
    - Style Guides: styleguides.md
  - Strategies:
    - Strategies: strategies.md
    - Topic-based writing: topic-basedwriting.md
    - Markdown writing: markdowntips.md
  - Blogs and Videos: 
    - Blogs: blogs.md
    - Videos: videos.md
  - About Me: aboutme.md
theme: 
  name: material
  features:
    - navigation.tabs
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.details