site_name: Resources for Technical Writers
nav:
  - Home: index.md
  - Blogs: blogs.md
  - Videos: videos.md
  - Markdown Tips: markdowntips.md
  - Flare: madcapflarebasics.md
  - MkDocs: mkdocstips.md
  - Topic-Based Writing: topic-basedwriting.md
theme: 
  name: material
  features:
    - navigation.tabs